In [1]:
import pandas as pd
df_finanzas = pd.read_csv(r"C:\Users\user\Downloads\catalogo_cf.csv", nrows = 1000000)

In [3]:
df_finanzas.columns

Index(['Nombre de la serie ', 'N�mero secuencial', 'Alias de la serie',
       'Nombre del archivo con los valores de la serie',
       'Descripci�n de la serie', 'Tipo de variable', 'C�digo de unidades',
       'Exponente', 'N�mero de decimales',
       'Descripci�n de unidades y exponente', 'Frecuencia de la serie',
       'Fecha de la primera observaci�n', 'Fecha de la �ltima observaci�n',
       'N�mero de observaciones', 'T�tulo de la serie', 'Fuente', 'Notas'],
      dtype='object')

In [4]:
df_finanzas['Nombre de la serie '].head()
#Busca la columna y muestra solo los primeros

0     DSPC102016CP30000_ES1_VCNTRA.T
1           DSPC102016CP30000_ES14.T
2           DSPC102016CP30000_ES15.T
3    DSPC102016CP30000_ES13_VCNTRA.T
4     DSPC102016CP51000_ES1_VCNTRA.T
Name: Nombre de la serie , dtype: object

In [5]:
df_finanzas[113:257]
#Muestra las filas en el rango

,Nombre de la serie,N�mero secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripci�n de la serie,Tipo de variable,C�digo de unidades,Exponente,N�mero de decimales,Descripci�n de unidades y exponente,Frecuencia de la serie,Fecha de la primera observaci�n,Fecha de la �ltima observaci�n,N�mero de observaciones,T�tulo de la serie,Fuente,Notas
113,DSPC102016CD80000_RS14A.T,3777635,CF_1_12.11,CF0112.csv,CNE. Base 2016. Ajuste variaci�n participaci�n...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
114,DSPC102016CD90000_RS14A.T,3777647,CF_1_12.12,CF0112.csv,CNE. Base 2016. Transferencias de capital a co...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
115,DSPC102016CD9OT00_RS14A.T,3777667,CF_1_12.13,CF0112.csv,CNE. Base 2016. Transferencias de capital a co...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
116,DSPC102016CD90000_ES14A.T,3777640,CF_1_12.14,CF0112.csv,CNE. Base 2016. Transferencias de capital a pa...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
117,DSPC102016CD91000_ES14A.T,3777652,CF_1_12.15,CF0112.csv,CNE. Base 2016. Transferencias de capital a pa...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,DSPC102016VB1B000_SS1_ARSER_TSC.T,3778069,CF_1_6.5,CF0106.csv,CNE. Base 2016. VAB. Servicios. �ndice de volu...,SUMA,Base_2016=100,0,2,Base_2016=100,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
253,DSPC102016VB1B000_SS1_ARCTH_TSC.T,3778061,CF_1_6.6,CF0106.csv,"CNE. Base 2016. VAB. Comercio, transporte y ho...",SUMA,Base_2016=100,0,2,Base_2016=100,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
254,DSPC102016VB1B000_SS1_ARICO_TSC.T,3778063,CF_1_6.7,CF0106.csv,CNE. Base 2016. VAB. Informaci�n y comunicacio...,SUMA,Base_2016=100,0,2,Base_2016=100,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
255,DSPC102016VB1B000_SS1_ARAFS_TSC.T,3778049,CF_1_6.8,CF0106.csv,CNE. Base 2016. VAB. Actividades financieras y...,SUMA,Base_2016=100,0,2,Base_2016=100,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
256,DSPC102016VB1B000_SS1_ARAIN_TSC.T,3778053,CF_1_6.9,CF0106.csv,CNE. Base 2016. VAB. Actividades inmobiliarias...,SUMA,Base_2016=100,0,2,Base_2016=100,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN

In [6]:
df_finanzas[df_finanzas['C�digo de unidades'] == 'EUR']
#Muestra la base que cumple con la condicion

,Nombre de la serie,N�mero secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripci�n de la serie,Tipo de variable,C�digo de unidades,Exponente,N�mero de decimales,Descripci�n de unidades y exponente,Frecuencia de la serie,Fecha de la primera observaci�n,Fecha de la �ltima observaci�n,N�mero de observaciones,T�tulo de la serie,Fuente,Notas
0,DSPC102016CP30000_ES1_VCNTRA.T,3777714,CF_1_1.1,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Precio...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
1,DSPC102016CP30000_ES14.T,3777708,CF_1_1.2,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Hogare...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
2,DSPC102016CP30000_ES15.T,3777711,CF_1_1.3,CF0101.csv,CNE. Base 2016. Gasto en consumo final. ISFLSH...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3,DSPC102016CP30000_ES13_VCNTRA.T,3777707,CF_1_1.4,CF0101.csv,CNE. Base 2016. Gasto en consumo final. AAPP. ...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
4,DSPC102016CP51000_ES1_VCNTRA.T,3777761,CF_1_1.5,CF0101.csv,CNE. Base 2016. Formaci�n bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3701,DMZ10F120B0.Q,2209065,CF_2_9B.27,CF029B.csv,CFEE. SEC2010. Flujo. Otros dep�sitos. Activo ...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodolog�a SEC2010/Operac...,Banco de Espa�a,NaN
3702,DMZ10F500B0.Q,2210757,CF_2_9B.28,CF029B.csv,CFEE. SEC2010. Flujo. Participaciones en el ca...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodolog�a SEC2010/Operac...,Banco de Espa�a,NaN
3703,DMZ10F530B0.Q,2211725,CF_2_9B.29,CF029B.csv,CFEE. SEC2010. Flujo. Otras participaciones. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodolog�a SEC2010/Operac...,Banco de Espa�a,NaN
3704,DMZ10F300B0.Q,2209505,CF_2_9B.30,CF029B.csv,CFEE. SEC2010. Flujo. Otros activos/pasivos. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodolog�a SEC2010/Operac...,Banco de Espa�a,NaN
3705,DMZ10F310B0.Q,2209810,CF_2_9B.31,CF029B.csv,CFEE. SEC2010. Flujo. Otras ctas. pte. de cobr...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodolog�a SEC2010/Operac...,Banco de Espa�a,NaN

In [7]:
df_finanzas[(df_finanzas['C�digo de unidades'] == 'EUR') & (df_finanzas['N�mero de decimales'] > 2)]
#Muestra la base que cumple la condicion, con & deben cumplirse ambas y con | solo una

,Nombre de la serie,N�mero secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripci�n de la serie,Tipo de variable,C�digo de unidades,Exponente,N�mero de decimales,Descripci�n de unidades y exponente,Frecuencia de la serie,Fecha de la primera observaci�n,Fecha de la �ltima observaci�n,N�mero de observaciones,T�tulo de la serie,Fuente,Notas
105,DSPC102016CD10000_RS14A.T,3777345,CF_1_12.3,CF0112.csv,CNE. Base 2016. Remuneraci�n de los asalariado...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
106,DSPC102016CD40000_RS14A.T,3777421,CF_1_12.4,CF0112.csv,CNE. Base 2016. Rentas de la propiedad. Hogare...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
125,DSPC102016CD40000_ES14A.T,3777414,CF_1_12.23,CF0112.csv,CNE. Base 2016. Rentas de la propiedad. Hogare...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
128,DSPC102016CD50000_ES14A.T,3777518,CF_1_12.26,CF0112.csv,"CNE. Base 2016. Impuestos sobre la renta, el p...",SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
135,DSPC102016CP51C00_ES14A.T,3777766,CF_1_12.33,CF0112.csv,CNE. Base 2016. Formaci�n bruta de capital fij...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
137,DSPC102016CNP0000_ES14A.T,3777672,CF_1_12.35,CF0112.csv,CNE. Base 2016. Adquisiciones menos cesiones d...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
140,DSPC102016CB2B3B0_SS14A.T,3777283,CF_1_12.38,CF0112.csv,CNE. Base 2016. Excedente bruto de explotaci�n...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
142,DSPC102016CB6B000_SS14A.T,3777293,CF_1_12.40,CF0112.csv,CNE. Base 2016. Renta disponible bruta. Hogare...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
144,DSPC102016CB8B000_SS14A.T,3777303,CF_1_12.42,CF0112.csv,CNE. Base 2016. Ahorro bruto. Hogares e ISFLSH,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
146,DSPC102016CB90000_SS14A.T,3777310,CF_1_12.44,CF0112.csv,CNE. Base 2016. Capacidad (+)/Necesidad (-) de...,SUMA,EUR,6,6,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN

In [13]:
df_finanzas[df_finanzas.Notas.isin(['NaN', 'HOLA'])].head()
# busca en el dataframe, la columna mencionada y muestra las filas en las que la columna cumpla la condicion de estar en la lista

Empty DataFrame
Columns: [Nombre de la serie , N�mero secuencial, Alias de la serie, Nombre del archivo con los valores de la serie, Descripci�n de la serie, Tipo de variable, C�digo de unidades, Exponente, N�mero de decimales, Descripci�n de unidades y exponente, Frecuencia de la serie, Fecha de la primera observaci�n, Fecha de la �ltima observaci�n, N�mero de observaciones, T�tulo de la serie, Fuente, Notas]
Index: []

In [14]:
df_finanzas[pd.isna(df_finanzas['Notas'])].head()
#usa el paquete pandas para ver cuando no hay nada en la columna que se necesita

,Nombre de la serie,N�mero secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripci�n de la serie,Tipo de variable,C�digo de unidades,Exponente,N�mero de decimales,Descripci�n de unidades y exponente,Frecuencia de la serie,Fecha de la primera observaci�n,Fecha de la �ltima observaci�n,N�mero de observaciones,T�tulo de la serie,Fuente,Notas
0,DSPC102016CP30000_ES1_VCNTRA.T,3777714,CF_1_1.1,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Precio...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
1,DSPC102016CP30000_ES14.T,3777708,CF_1_1.2,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Hogare...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
2,DSPC102016CP30000_ES15.T,3777711,CF_1_1.3,CF0101.csv,CNE. Base 2016. Gasto en consumo final. ISFLSH...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3,DSPC102016CP30000_ES13_VCNTRA.T,3777707,CF_1_1.4,CF0101.csv,CNE. Base 2016. Gasto en consumo final. AAPP. ...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
4,DSPC102016CP51000_ES1_VCNTRA.T,3777761,CF_1_1.5,CF0101.csv,CNE. Base 2016. Formaci�n bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripci�n Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN

In [15]:
len(df_finanzas[pd.isna(df_finanzas['Notas'])])
#Mirar en cuantas filas la columna seleccionada no tiene ningun valor

3706