In [1]:
# -*- coding: utf-8 -*-
import pandas as pd
df_finance = pd.read_csv(r"C:\Users\user\Downloads\catalogo_cf.csv", encoding='iso-8859-1', nrows = 1000000)
#nrows=1e6 un millon de filas

In [2]:
df_duplicate = df_finance.append(df_finance)

In [3]:
df_duplicate = df_duplicate.sample(frac=1)
#la base duplicada es solo una muestra al azar de la base

In [4]:
df_clean = df_duplicate.drop_duplicates()
#elimina todos los casos duplicados

In [8]:
len(df_clean) == len(df_finance)

True

In [6]:
df_clean.drop_duplicates(subset = 'Nombre de la serie ')
#Elimina los duplicados que hay en nombre de la serie

,Nombre de la serie,Número secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripción de la serie,Tipo de variable,Código de unidades,Exponente,Número de decimales,Descripción de unidades y exponente,Frecuencia de la serie,Fecha de la primera observación,Fecha de la última observación,Número de observaciones,Título de la serie,Fuente,Notas
962,DMZ10F800F0.Q,2211849,CF_2_16B.28,CF0216.csv,CFEE. SEC2010. Flujo. Préstamos. Activo de tod...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Series de Cuentas Financiers (DMZ - nueva nome...,Banco de España,NaN
161,DSPC102016CD56700_ES1_RS2.T,3777529,CF_1_14.8,CF0114.csv,CNE. Base 2016. Transferencias corrientes. Tot...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
901,DMZ10S4000F.Q,2216066,CF_2_16A.6,CF0216.csv,CFEE. SEC2010. Saldo. Valores representativos ...,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Series de Cuentas Financiers (DMZ - nueva nome...,Banco de España,NaN
999,DMZ10S410T0.Q,2216299,CF_2_17A.26,CF0217.csv,CFEE. SEC2010. Saldo. Valores. A corto plazo. ...,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Series de Cuentas Financiers (DMZ - nueva nome...,Banco de España,NaN
691,DMZ10S512Q0.Q,2377040,CF_2_13A.33,CF0213.csv,CFEE. SEC2010. Saldo. Acciones no cotizadas. ...,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Cuentas Financieras/Metodología SEC2010/Saldo/...,Banco de España,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,DSPC102016CP51000_ES1.T,3777738,CF_1_8.18,CF0108.csv,CNE. Base 2016. Formación bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1999,MAR 2021,89,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3388,DMZ10S8400N.Q,2218407,CF_2_6A.21,CF026A.csv,CFEE. SEC2010. Saldo. Créditos comerciales y a...,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Cuentas Financieras/Metodología SEC2010/Saldo/...,Banco de España,NaN
541,DMZ10S310L0.Q,2215859,CF_2_11A.45,CF0211.csv,CFEE. SEC2010. Saldo. Otras ctas. pte. de cobr...,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Cuentas Financieras/Metodología SEC2010/Saldo/...,Banco de España,NaN
720,DMZ10F400Q0.Q,2376738,CF_2_13B.24,CF0213.csv,CFEE. SEC2010. Flujo. Valores representativos ...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3482,DMZ10S130A0.Q,2215214,CF_2_7A.33,CF027A.csv,CFEE. SEC2010. Saldo. Depósitos transferibles....,FINAL,EUR,3,0,Miles de Euros,TRIMESTRAL,DIC 1994,MAR 2021,106,Cuentas Financieras/Metodología SEC2010/Saldo/...,Banco de España,NaN

In [7]:
df_finance.dropna()
#me arroja todas las filas del dataframe que no tenga ningun dato faltante

Empty DataFrame
Columns: [Nombre de la serie , Número secuencial, Alias de la serie, Nombre del archivo con los valores de la serie, Descripción de la serie, Tipo de variable, Código de unidades, Exponente, Número de decimales, Descripción de unidades y exponente, Frecuencia de la serie, Fecha de la primera observación, Fecha de la última observación, Número de observaciones, Título de la serie, Fuente, Notas]
Index: []

In [10]:
df_finance.dropna(thresh=5 )
#Cuantos columnas pueden estar vacias por fila y me muestra solo los que tienen mas de eso

,Nombre de la serie,Número secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripción de la serie,Tipo de variable,Código de unidades,Exponente,Número de decimales,Descripción de unidades y exponente,Frecuencia de la serie,Fecha de la primera observación,Fecha de la última observación,Número de observaciones,Título de la serie,Fuente,Notas
0,DSPC102016CP30000_ES1_VCNTRA.T,3777714,CF_1_1.1,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Precio...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
1,DSPC102016CP30000_ES14.T,3777708,CF_1_1.2,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Hogare...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
2,DSPC102016CP30000_ES15.T,3777711,CF_1_1.3,CF0101.csv,CNE. Base 2016. Gasto en consumo final. ISFLSH...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3,DSPC102016CP30000_ES13_VCNTRA.T,3777707,CF_1_1.4,CF0101.csv,CNE. Base 2016. Gasto en consumo final. AAPP. ...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
4,DSPC102016CP51000_ES1_VCNTRA.T,3777761,CF_1_1.5,CF0101.csv,CNE. Base 2016. Formación bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3701,DMZ10F120B0.Q,2209065,CF_2_9B.27,CF029B.csv,CFEE. SEC2010. Flujo. Otros depósitos. Activo ...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3702,DMZ10F500B0.Q,2210757,CF_2_9B.28,CF029B.csv,CFEE. SEC2010. Flujo. Participaciones en el ca...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3703,DMZ10F530B0.Q,2211725,CF_2_9B.29,CF029B.csv,CFEE. SEC2010. Flujo. Otras participaciones. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3704,DMZ10F300B0.Q,2209505,CF_2_9B.30,CF029B.csv,CFEE. SEC2010. Flujo. Otros activos/pasivos. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3705,DMZ10F310B0.Q,2209810,CF_2_9B.31,CF029B.csv,CFEE. SEC2010. Flujo. Otras ctas. pte. de cobr...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN

In [11]:
df_finance.dropna(thresh=len(df_finance.columns)-1 )
#Cuantas columnas pueden estar vacias por filas

,Nombre de la serie,Número secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripción de la serie,Tipo de variable,Código de unidades,Exponente,Número de decimales,Descripción de unidades y exponente,Frecuencia de la serie,Fecha de la primera observación,Fecha de la última observación,Número de observaciones,Título de la serie,Fuente,Notas
0,DSPC102016CP30000_ES1_VCNTRA.T,3777714,CF_1_1.1,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Precio...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
1,DSPC102016CP30000_ES14.T,3777708,CF_1_1.2,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Hogare...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
2,DSPC102016CP30000_ES15.T,3777711,CF_1_1.3,CF0101.csv,CNE. Base 2016. Gasto en consumo final. ISFLSH...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3,DSPC102016CP30000_ES13_VCNTRA.T,3777707,CF_1_1.4,CF0101.csv,CNE. Base 2016. Gasto en consumo final. AAPP. ...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
4,DSPC102016CP51000_ES1_VCNTRA.T,3777761,CF_1_1.5,CF0101.csv,CNE. Base 2016. Formación bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3701,DMZ10F120B0.Q,2209065,CF_2_9B.27,CF029B.csv,CFEE. SEC2010. Flujo. Otros depósitos. Activo ...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3702,DMZ10F500B0.Q,2210757,CF_2_9B.28,CF029B.csv,CFEE. SEC2010. Flujo. Participaciones en el ca...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3703,DMZ10F530B0.Q,2211725,CF_2_9B.29,CF029B.csv,CFEE. SEC2010. Flujo. Otras participaciones. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3704,DMZ10F300B0.Q,2209505,CF_2_9B.30,CF029B.csv,CFEE. SEC2010. Flujo. Otros activos/pasivos. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3705,DMZ10F310B0.Q,2209810,CF_2_9B.31,CF029B.csv,CFEE. SEC2010. Flujo. Otras ctas. pte. de cobr...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN

In [12]:
df_finance.dropna(subset = ['Descripción de la serie'])
#Me muestra las filas del dataframe que no tengan vacia la columna especificada

,Nombre de la serie,Número secuencial,Alias de la serie,Nombre del archivo con los valores de la serie,Descripción de la serie,Tipo de variable,Código de unidades,Exponente,Número de decimales,Descripción de unidades y exponente,Frecuencia de la serie,Fecha de la primera observación,Fecha de la última observación,Número de observaciones,Título de la serie,Fuente,Notas
0,DSPC102016CP30000_ES1_VCNTRA.T,3777714,CF_1_1.1,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Precio...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
1,DSPC102016CP30000_ES14.T,3777708,CF_1_1.2,CF0101.csv,CNE. Base 2016. Gasto en consumo final. Hogare...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
2,DSPC102016CP30000_ES15.T,3777711,CF_1_1.3,CF0101.csv,CNE. Base 2016. Gasto en consumo final. ISFLSH...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
3,DSPC102016CP30000_ES13_VCNTRA.T,3777707,CF_1_1.4,CF0101.csv,CNE. Base 2016. Gasto en consumo final. AAPP. ...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
4,DSPC102016CP51000_ES1_VCNTRA.T,3777761,CF_1_1.5,CF0101.csv,CNE. Base 2016. Formación bruta de capital fij...,SUMA,EUR,6,0,Millones de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Descripción Familia: Contabilidad nacional de...,Instituto Nacional de Estadistica,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3701,DMZ10F120B0.Q,2209065,CF_2_9B.27,CF029B.csv,CFEE. SEC2010. Flujo. Otros depósitos. Activo ...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3702,DMZ10F500B0.Q,2210757,CF_2_9B.28,CF029B.csv,CFEE. SEC2010. Flujo. Participaciones en el ca...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3703,DMZ10F530B0.Q,2211725,CF_2_9B.29,CF029B.csv,CFEE. SEC2010. Flujo. Otras participaciones. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3704,DMZ10F300B0.Q,2209505,CF_2_9B.30,CF029B.csv,CFEE. SEC2010. Flujo. Otros activos/pasivos. A...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN
3705,DMZ10F310B0.Q,2209810,CF_2_9B.31,CF029B.csv,CFEE. SEC2010. Flujo. Otras ctas. pte. de cobr...,SUMA,EUR,3,0,Miles de Euros,TRIMESTRAL,MAR 1995,MAR 2021,105,Cuentas Financieras/Metodología SEC2010/Operac...,Banco de España,NaN